#!/usr/bin/env python
#
# Call the command line interface for Epydoc.
#

# Make sure that we don't get confused between an epycsdoc.py script and
# the real epycsdoc package.
import sys, os.path
if os.path.exists(os.path.join(sys.path[0], 'epycsdoc.py')):
    del sys.path[0]

from epycsdoc.cli import cli
cli()

